# Generated by Django 4.2.1 on 2023-06-27 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("video", "0002_videolike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("FOLLOW", "follow"),
                            ("COMMENT", "comment"),
                            ("LIKE", "like"),
                            ("SHARED", "shared"),
                        ],
                        max_length=255,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_user_follower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.video",
                    ),
                ),
            ],
        ),
    ]
