# Generated by Django 4.2.1 on 2023-06-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_alter_notification_type_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("FOLLOW", "follow"),
                    ("COMMENT", "comment"),
                    ("LIKE", "like"),
                    ("SHARED", "shared"),
                ],
                max_length=255,
            ),
        ),
    ]
